name: Update GitHub Streak

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-streak:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate streak
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python generate_streak.py

      - name: Commit SVG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add streak.svg

          git diff --cached --quiet || git commit -m "Update GitHub streak"

          git push
